# Author: Brady M. Chisholm
# University of Minnesota Twin Cities
# Department of Psychology

# libraries
```{r}
library(R.matlab)   # To read .mat data files
library(mgcv)       # For GAMM analysis
library(knitr)      # purl(); source .Rmd code for callins funcitons   
```

# get subject ID list 
```{r}
purl("M:/Lab_Shared/Brady_C/Projects/pupilEEG_fatigue/statistics/scripts/getSubjID_RV.Rmd",
     output = "getSubjID_RV.R")
source("getSubjID_RV.R")
subjIDS <- getSubjList(1)
```

# folder structure
```{r}
# Base directory
base_dir <- "M:/Lab_Shared/Juraj/SpeechEEG_SentencesWithPupillometry"
folderName <- "data" 
```

```{r}
# empty list for data 
allDat_list <- list()
```

# subj loop 
```{r}
for (subj in subjIDS) {
  # build file path 
  file_path <- file.path(base_dir, folderName, subj, "eyeTrack", "processed", paste0(subj, "_preprocPupilData.mat"))
  
  # check existence 
  if (!file.exists(file_path)) {
    warning("File does not exist for subject: ", subj)
    next
  }
  
  # read mat file 
  mat_data <- readMat(file_path)
  
  # check existence
  if (!"allDat" %in% names(mat_data)) {
    warning("Subject ", subj, ": Variable 'allDat' not found in the .mat file.")
    next
  }
  
  # Extract "allDat"; [200 x 2 x 6000]
  allDat <- mat_data$allDat
  
  # check dims 
  if (!all(dim(allDat) == c(200, 2, 6000))) {
    warning("Subject ", subj, ": 'allDat' dims != [200 x 2 x 6000]")
  }
  
  # store array w/ subject ID as name
  allDat_list[[subj]] <- allDat
}
```

```{r}
#print final structure 
cat("Total subjects loaded:", length(allDat_list), "\n")

# print ending dims 
for (subj in names(allDat_list)) {
  cat("Subject:", subj, " - Dimensions:", paste(dim(allDat_list[[subj]]), collapse = " x "), "\n")
  }
```
